### ISSUE TITLE
Bot Learning

### ISSUE THREAD

**Issue by Vishal-7** [keiffster/program-y#126]
Whenever i use the learnf function, the learnf.aiml file gets created in y-bot folder and not in the aiml folder in y-bot. How do i get to save the y-bot-learnf.aiml file into the aiml folder? Thanks in advance

**Comment by keiffster** [comment]
Use the learn-filename config setting of the defaults section of brain as follows

```yaml
brain:
    defaults:
      learn-filename: y-bot-learnf.aiml
```

Change this to a full or relative path to the file you want to create

K
