### ISSUE TITLE
External REST (<sraix>) does not seems to pass parameters 

### ISSUE THREAD

**Issue by ohoachuck** [keiffster/program-y#140]
Trying to get [external REST](https://github.com/keiffster/program-y/wiki/External-Rest) \<sraix\> call. But this is without success. ;( 
Is there something I do wrong ?

## Expected Behavior
Be able to call external REST service.

## Current Behavior
I have set a local flask HTTP server.
My http://localhost:8888/api/v1.0/ask is get called but I feel like no params are passed.

## Possible Solution
no idea ;(

## Steps to Reproduce
use tag like this:
```xml
<category>
    <pattern>ASKOTHERSERVICE *</pattern>
    <template>
        <sraix service="rest"><star /></sraix>
    </template>
</category>
```

Config.yaml file is:
```yaml
    services:
        REST:
            classname: programy.services.rest.GenericRESTService
            method: GET
            host: 0.0.0.0
            port: 8888
            url: /api/v1.0/ask
```

Properties.txt file state:
```
...
pannous: true
pandora: true
wikipedia: true
duckduckgo: true
newsapi: true
weather: true
mapping: true
geocode: true
rest: true
...
```
## Context (Environment)
* Version of Y-Bot: latest version
* Version of Python: Python 3.6
* Operating System ( inc Version ): mac OS
