### ISSUE TITLE
Multiple bots and brains

### ISSUE THREAD

**Issue by utuxmt** [keiffster/program-y#169]
I want to serve REST client with multiple bots, for example, bot1 and bot2, each has its own brain brain1 and brain2. The *config.yml* looks like

``` yaml
rest:
   bot: |
      bot1
      bot2
   port: 8989
   ...

bot1:
   brain: brain1
   ...

bot2:
   brain: brain2
   ...

brain1:
   files:
      aiml:
         files: $BOT_ROOT/bot1/aiml
   ...

brain2:
   files:
      aiml:
         files: $BOT_ROOT/bot2/aiml
   ...
```

## Expected Behavior
I expect when I run the service, either bot1 or bot2 will be served as default. Therefore, the request will be processed by on of the bots.

## Current Behavior
I can successfully get response from program-y, with correct question and userid I gave, but the *answer* field is always an empty string.  
``` json
[
   {
      "response": {
         "answer": "",
         "question": "hello world",
         "userid": "123"
      }
   }, 
   200
]
```

## Steps to Reproduce
1. *config.yml* as above,  *bot1/aiml* and *bot2/aiml* are needed to reproduce the problem.
2. Move to the bot directory
3. Run service with python3 -m programy.clients.restful.flask.client --config ./config.yaml --cformat yaml --logging ./logging.yaml
4. `curl http://localhost:8989/api/rest/v1.0/ask\?question\=hello+world\&userid\=123`

## Context (Environment)
* Version of Y-Bot: not sure the version is, but cloned on Aug. 2018
* Version of Python:  python-3.6
* Operating System ( inc Version ): Ubuntu 18.04
