### ISSUE TITLE
User's properties convo file got deleted although `empty_on_start` is `false`

### ISSUE THREAD

**Issue by elcolie** [keiffster/program-y#170]
## Expected Behavior

`$BOT_ROOT/CONVERSATIONS/file.convo` persist and next conversation will concatenate it

## Current Behavior
It got deleted

## Possible Solution
Use just one conversation log per time. I am using `/tmp/y-bot-conversation.csv` for full log.
And user's properties log.

## Steps to Reproduce
Focus on `brain/files/aiml/conversations`

```yml
brain:

    # Overrides
    overrides:
      allow_system_aiml: true
      allow_learn_aiml: true
      allow_learnf_aiml: true

    # Defaults
    defaults:
      default-get: unknown
      default-property: unknown
      default-map: unknown
      learnf-path: $BOT_ROOT/aimlf

    # Nodes
    nodes:
      pattern_nodes: $BOT_ROOT/config/pattern_nodes.conf
      template_nodes: $BOT_ROOT/config/template_nodes.conf

    # Binary
    binaries:
      save_binary: false
      load_binary: false
      binary_filename: /tmp/y-bot.brain
      load_aiml_on_binary_fail: false

    # Braintree
    braintree:
      file: /tmp/braintree.xml
      content: xml

    files:
        aiml:
            files: $BOT_ROOT/aiml
            extension: .aiml
            directories: true
            errors:
              file: /tmp/y-bot_errors.csv
              format: csv
              encoding: utf-8
              delete_on_start: false
            duplicates:
              file: /tmp/y-bot_duplicates.csv
              format: csv
              encoding: utf-8
              delete_on_start: false
            conversations:
              # conversation log
              file: /tmp/y-bot-conversation.csv
              format: csv
              delete_on_start: false

              # User's properties
              type: file
              config_name: file_storage
              empty_on_start: false
              file_storage:
                dir: $BOT_ROOT/conversations
            # Bot's properties
            properties: $BOT_ROOT/config/properties.txt
```

## Context (Environment)
programy==2.2
Python3.7.0
OSX 10.13.5

User's properties convo file got deleted although `empty_on_start` is `false`

## Possible Implementation
Use one log per time not both
