### ISSUE TITLE
Adding Arabic punctuation in the list of filtered punctuation characters

### ISSUE THREAD

**Issue by Algeneralo** [keiffster/program-y#216]
## Possible Solution

Adding "؟" this punctuation to filter

**Comment by keiffster** [comment]
You can add this without any code modifications into the config into the bot section of your config.yaml

```yaml
bot:
  splitter:
   split_chars: :;,.?!؟
```
