### ISSUE TITLE
openchatbots config documentation for supported domains should be updated

### ISSUE THREAD

**Issue by ohoachuck** [keiffster/program-y#277]
Documentation for openchatbots config file is not correct here : https://github.com/keiffster/program-y/wiki/Open-Chatbot

Current config example in Wiki (wrong):
```yaml
 openchatbots:
      protocols: http, https
      domains: org, co.uk
```

Should be :
```yaml
 openchatbots:
      protocols: ["http", "https"]
      domains: ["org", "co.uk"]
```
