### ISSUE TITLE
How to Contribute?

### ISSUE THREAD

**Issue by acondori** [keiffster/program-y#64]
Hello! I want to contribute with a Spanish version but I do not know how to start. My idea is to initially translate what already exists in English for example: Hi! --> Hola! ; Hi, how can I help you today? --> Hola! Cómo puedo ayudarte?  What do you suggest I do?

Cheers!!!

**Comment by acondori** [comment]
I mean, if I translate all AIML from Alice2 is enough?
What else should I think about?
[https://github.com/keiffster/program-y/tree/b20c7dc64dddf949e588c22b43457c179b24f294/bots/alice2/aiml](url)

**Comment by keiffster** [comment]
Great news that you want to help improve Program-Y, and having just returned from 2 weeks in sunny Spain, it would be great to see a Spanish version of the grammar.

Your best way to get started is to make a copy of Alice2, maybe call it Alice2_es and convert all text in the files to Spanish. The only other location that contains some text is config.yaml which has some default response, but I have plans to move these into the grammar files too.

We can use your journey converting to Spanish to create a set of lessons learnt for others wanting to do other languages.

I'll keep an eye on your branch to see how you get on, but feel free to raise any issues and questions   through GitHub and I'll respond as soon as I can

Good luck!

**Comment by acondori** [comment]
Okey, I`ll star!
How can I test each .aiml file?
I'm going to start in order and the first one is this:
program-y/bots/alice2/aiml/animal.aiml

Thanks you!

**Comment by keiffster** [comment]
There is a feature you can use to tell the bot to load only one file

I'll add the documentation later but instead of using files in the aiml section and giving it a path, use file and give it the path to a single file

The bot will then only load that file

K

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630

**Comment by keiffster** [comment]
Updated config file with description of how to use files vs file

https://github.com/keiffster/program-y/wiki/Config_Brain_Files/_edit

**Comment by acondori** [comment]
Thanks a lot! I'll do my best! Cheers!

**Comment by acondori** [comment]
Sorry!!!!

This is okey?

> brain:
> 
>     supress_warnings: true
> 
>     allow_system_aiml: true
>     allow_learn_aiml: true
>     allow_learnf_aiml: true
> 
>     files:
>         aiml:
>             file: $BOT_ROOT/aiml/animal.aiml
>         sets:
>             files: $BOT_ROOT/sets
>             extension: .txt
>             directories: false
>         maps:
>             files: $BOT_ROOT/maps
>             extension: .txt
>             directories: false
>         denormal: $BOT_ROOT/config/denormal.txt
>         normal: $BOT_ROOT/config/normal.txt
>         gender: $BOT_ROOT/config/gender.txt
>         person: $BOT_ROOT/config/person.txt
>         person2: $BOT_ROOT/config/person2.txt
>         predicates: $BOT_ROOT/config/predicates.txt
>         pronouns: $BOT_ROOT/config/pronouns.txt
>         properties: $BOT_ROOT/config/properties.txt
>         triples: $BOT_ROOT/config/triples.txt
>         preprocessors: $BOT_ROOT/config/preprocessors.conf
>         postprocessors: $BOT_ROOT/config/postprocessors.conf

When I do that, I got this message:


> Loading, please wait...
> No bot root argument set, defaulting to [.]
> Traceback (most recent call last):
>   File "../../src/programy/clients/console.py", line 51, in <module>
>     run()
>   File "../../src/programy/clients/console.py", line 48, in run
>     console_app = ConsoleBotClient()
>   File "../../src/programy/clients/console.py", line 8, in __init__
>     BotClient.__init__(self)
>   File "/Users/acondori/chapi/program-y/src/programy/clients/clients.py", line 82, in __init__
>     self.load_configuration(self.arguments)
>   File "/Users/acondori/chapi/program-y/src/programy/clients/clients.py", line 126, in load_configuration
>     arguments.config_format, arguments.bot_root)
>   File "/Users/acondori/chapi/program-y/src/programy/config/file/factory.py", line 31, in load_configuration_from_file
>     config_file.load_from_file(filename, bot_root)
>   File "/Users/acondori/chapi/program-y/src/programy/config/file/yaml.py", line 37, in load_from_file
>     self.client_config.load_config_data(self, bot_root)
>   File "/Users/acondori/chapi/program-y/src/programy/config/client/client.py", line 36, in load_config_data
>     self._brain_config.load_config_section(config_file, bot_root)
>   File "/Users/acondori/chapi/program-y/src/programy/config/brain.py", line 119, in load_config_section
>     self._aiml_files = self._get_brain_file_configuration(config_file, aiml, bot_root)
>   File "/Users/acondori/chapi/program-y/src/programy/config/brain.py", line 101, in _get_brain_file_configuration
>     files = self.sub_bot_root(files, bot_root)
>   File "/Users/acondori/chapi/program-y/src/programy/config/base.py", line 33, in sub_bot_root
>     return text.replace('$BOT_ROOT', root)
> AttributeError: 'NoneType' object has no attribute 'replace'
> 
> 

Can you help me? 

Cheers!!

**Comment by keiffster** [comment]
Looks like you are using an earlier version of y-bot prior to the config refactoring.

I would take the latest code from master from git and then try again, I just tried the following config file and its alls working

```

brain:

    # Overrides
    overrides:
      allow_system_aiml: true
      allow_learn_aiml: true
      allow_learnf_aiml: true

    # Defaults
    # These have not been added to the system yet
    defaults:
      default-get: unknown
      default-property: unknown
      default-map: unknown
      learn-filename: alice2-learnf.aiml
    # These have not been added to the system yet

    # Nodes
    nodes:
      pattern_nodes: $BOT_ROOT/config/pattern_nodes.conf
      template_nodes: $BOT_ROOT/config/template_nodes.conf

    # Binary
    binaries:
      save_binary: false
      load_binary: false
      binary_filename: /tmp/alice2.brain
      load_aiml_on_binary_fail: false
      dump_to_file: /tmp/braintree.txt

    files:
        aiml:
            #files: $BOT_ROOT/aiml
            file: $BOT_ROOT/aiml/animal.aiml
            extension: .aiml
            directories: true
            errors: /tmp/alice2_errors.txt
            duplicates: /tmp/alice2_duplicates.txt
        sets:
            files: $BOT_ROOT/sets
            extension: .txt
            directories: false
        maps:
            files: $BOT_ROOT/maps
            extension: .txt
            directories: false
        denormal: $BOT_ROOT/config/denormal.txt
        normal: $BOT_ROOT/config/normal.txt
        gender: $BOT_ROOT/config/gender.txt
        person: $BOT_ROOT/config/person.txt
        person2: $BOT_ROOT/config/person2.txt
        predicates: $BOT_ROOT/config/predicates.txt
        pronouns: $BOT_ROOT/config/pronouns.txt
        properties: $BOT_ROOT/config/properties.txt
        triples: $BOT_ROOT/config/triples.txt
        preprocessors: $BOT_ROOT/config/preprocessors.conf
        postprocessors: $BOT_ROOT/config/postprocessors.conf

    services:
        REST:
            classname: programy.utils.services.rest.GenericRESTService
            method: GET
            host: 0.0.0.0
        Pannous:
            classname: programy.utils.services.pannous.PannousService
            url: http://weannie.pannous.com/api
        Pandora:
            classname: programy.utils.services.pandora.PandoraService
            url: http://www.pandorabots.com/pandora/talk-xml
        Wikipedia:
            classname: programy.utils.services.wikipediaservice.WikipediaService

bot:
    license_keys: $BOT_ROOT/config/license.keys
    prompt: ">>>"
    initial_question: Hi, how can I help you today?
    default_response: Sorry, I don't have an answer for that!
    empty_string_srai: YEMPTY
    exit_response: So long, and thanks for the fish!
    override_predicates: true

    max_question_recursion: 1000
    max_question_timeout: 60
    max_search_depth: 100
    max_search_timeout: 60

    spelling:
      classname: programy.utils.spelling.checker.SpellingChecker
      corpus: $BOT_ROOT/spelling/corpus.txt
      check_before: false
      check_and_retry: false
```
