### ISSUE TITLE
Unicode setting in log files...

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#74]
Previous issue reminded me of another one.. I had to add utf-8 to log files to resolve an encoding error with dealing with unicode input or responses. 
```
handlers:
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        filename: /tmp/mybot.log
        maxBytes: 20972152
        backupCount: 10
        encoding: utf-8
```
Otherwise no other problems I recall with Unicode support.

Sean
