### ISSUE TITLE
Bot Learning

### ISSUE THREAD

**Issue by najmulislam** [keiffster/program-y#84]
Hi Keith,

I am new to bots and I want to add learning in the chat bot, I have tried with <learn> and <learnf> aiml tags it was working fine but whenever my server restarts all learning gets lost.
How can I enable/add learning process that can persist in the system or in file.

I am using xmpp protocol with ejabberd for my bot.

**Comment by keiffster** [comment]
Are  you using learn or learnf

The learn tag is transient and is lost when bot restarts, learnf writes the grammar to a new file as specified in the config items show below

```
brain:

    # Overrides
    overrides:
      allow_learnf_aiml: true                                                        

    # Defaults
    defaults:
      learn-filename: $BOT_ROOT/aiml/y-bot-learnf.aiml         
```

Make sure allow_learnf_aiml is set to true
Make sure learn-filename is set to a file that is picked up by the parser
